default: &default
  adapter: postgresql
  host: localhost
  database: schedule
  username: guedes
  password: '123456'
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default